### PR TITLE
feat: Support templates in expectations

### PR DESCRIPTION
**Pull request by hassy**
Fixes: https://github.com/shoreditch-ops/artillery/issues/570
Fixes: https://github.com/shoreditch-ops/artillery/issues/571

### CODE REVIEW

**Comment by hassy** [comment]
Thanks @kirksl! this is still a WIP. I'm not sure why Github closed the two linked issues before the PR is merged.

**Comment by kirksl** [comment]
@hassy no worries.  i've got a test ready to go when the PR is ready.

**Comment by hassy** [comment]
@kirksl the most recent updates should now work, but they require the latest version of Artillery (`1.6.0-26`). Let me know if you get a chance to run them on your test cases & thanks for the help with this PR!

**Comment by kirksl** [comment]
@hassy trying but running into other issues with the project.  tried both 1.6.0-26 and went back to 1.6.0-25.  any ideas?

when running "artillery run ./tests/script.yml" through an npm script.  no changes to previously working code i get -->
TypeError: Cannot read property '0' of undefined at result.vars[fieldName] = row[j];
    at c:\projects\consensys\node_modules\artillery\core\lib\runner.js:415:37
    at arrayEach (c:\projects\consensys\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (c:\projects\consensys\node_modules\lodash\lodash.js:9344:14)
    at c:\projects\consensys\node_modules\artillery\core\lib\runner.js:414:9
    at arrayEach (c:\projects\consensys\node_modules\lodash\lodash.js:516:11)

when running "artillery run ./tests/script.yml" directly from a command prompt i get -->
WARNING: plugin datadog specified but module artillery-plugin-datadog could not be loaded
WARNING: plugin expect specified but module artillery-plugin-expect could not be loaded
Started phase 0, duration: 1s @ 12:56:55(-0800) 2018-11-29
...
// all good output here except that i cannot verify this fix because the expect plugin does not load.
// i had this issue before as well but when running through npm it loaded just fine
...

**Comment by hassy** [comment]
Not sure what the first error might mean. For the second one - if you're running `artillery` which was installed globally (ie with `npm install -g`) then the plugins need to be installed globally too for Artillery to be able to find & load them.

**Comment by hassy** [comment]
There have been some changes to the default CSV parsing behavior in 1.6.0-26, e.g. it'll always skip empty lines now, but I don't think that should've caused an exception on the line in the stack trace...

**Comment by kirksl** [comment]
i think i understand the mismatch in behavior when running artillery straight or via npm.  i had installed artillery globally in the beginning with is 1.6.0-25 and had started using package.json to deploy the package moving forward.  when i upgraded to 1.6.0-26 my local project which npm taps into would use that one.  when i run artillery straight it would target the global version 1.6.0-25.  problem solved i've started fresh wiping out my global and project level node_modules.  i wonder though is it a bug that calling artillery directly does not try to run the local project version first?

regarding the exception i think there is a real bug in 1.6.0-26.  started over as i mentioned clearing out all node_modules and did this -->

// test completes as expected
npm install -g artillery@1.6.0-25
npm install -g artillery-plugin-datadog
npm install -g artillery-plugin-expect
artillery run .\tests\script.yml

// start over
npm uninstall -g artillery-plugin-expect
npm uninstall -g artillery-plugin-datadog
npm uninstall -g artillery

// test fails with same error (below)
npm install -g artillery@1.6.0-26
npm install -g artillery-plugin-datadog
npm install -g artillery-plugin-expect
artillery run .\tests\script.yml

- WARNING: plugin datadog specified but module artillery-plugin-datadog could not be loaded
Started phase 0, duration: 1s @ 16:53:31(-0800) 2018-11-29
/ C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:415
        result.vars[fieldName] = row[j];
                                    ^
TypeError: Cannot read property '0' of undefined
    at C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:415:37
    at arrayEach (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\node_modules\lodash\lodash.js:9344:14)
    at C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:414:9
    at arrayEach (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\node_modules\lodash\lodash.js:516:11)
    at Function.forEach (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\node_modules\lodash\lodash.js:9344:14)
    at createContext (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:412:7)
    at runScenario (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:373:27)
    at EventEmitter.<anonymous> (C:\Users\Kirk\AppData\Roaming\npm\node_modules\artillery\core\lib\runner.js:256:5)
    at EventEmitter.emit (events.js:182:13)

**Comment by hassy** [comment]
Thanks @kirksl. I'm able to reproduce that exact error if I use an empty CSV file:

1. An empty file triggers the error on both `1.6.0-25` and `1.6.0-26`
2. A file which contains blank lines but no other data triggers the error on `1.6.0-26` but **not** `1.6.0-25`

Can you confirm that your CSV has data in it?

This does not seem like an issue with the plugin anyway, so I'll merge this PR.

**Comment by kirksl** [comment]
@hassy yes my CSV does have data in it.  i've put yml and csv file details below that repro the issue on this latest version.  only the latest version.  25 works perfect.  let me know if you need any other details to repro.

// csv
"Happy: Street,City,State,Zip,Country","json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA+94043,+USA",37.422617,-122.085383
"Happy: Street,City,State,Zip","json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA+94043",37.422617,-122.0853839
"Happy: Street,City,State","json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA",37.422617,-122.0853839
"Happy: Street,City","json?address=1600+Amphitheatre+Parkway,+Mountain+View",37.422617,-122.0853839
"Happy: Street","json?address=1600+Amphitheatre+Parkway",37.422617,-122.0853839

// yml
config:
  target: https://maps.googleapis.com/maps/api
  payload:
    path: "happy.csv"
    fields:
      - "description"
      - "querystring"
      - "lat"
      - "lng"
    order: sequence
  http:
    timeout: 60
  phases:
    - duration: 1
      arrivalRate: 1
  ensure:
    p99: 10000
    median: 5000
  plugins:
    datadog:
      host: ""
      prefix: "artillery."
      tags:
        - "mode:test"
    expect: {}
scenarios:
  - flow:
    - log: "/geocode happy test --> {{ description }}"
    - get:
        url: "/geocode/{{ querystring }}&key={{ $processEnvironment.GOOGLE_API_KEY }}"
        capture:
          json: "$.results[0].geometry.location"
          as: "location"
        log: "{{ location.lat }}"
        expect:
          - statusCode: 200
          - contentType: json
          - equals:
            - "{{ location.lat }}"
            - "{{ lat }}"
          - equals:
            - "{{ location.lng }}"
            - "{{ lng }}"

**Comment by hassy** [comment]
@kirksl that's brilliant, thank you, I wish all bug reports came with that amount of detail. :) I'll create another issue in the main repo to track.

**Comment by kirksl** [comment]
@hassy happy to help!

**Pull request merged**
